# Generated by Django 4.1.7 on 2023-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, verbose_name='Ключ настройки')),
                ('value', models.CharField(max_length=500, verbose_name='Значение настройки')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'ordering': ['-id'],
            },
        ),
    ]
