# Generated by Django 4.1.7 on 2023-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrum_cloud_id', models.CharField(max_length=100, verbose_name='ID скрама в облаке')),
                ('scrum_box_id', models.CharField(max_length=100, verbose_name='ID скрама в коробке')),
                ('scrum_title', models.CharField(max_length=200, verbose_name='Название скрама')),
                ('scrum_master_id_cloud', models.CharField(max_length=100, verbose_name='ID скрам-мастера в облаке')),
                ('scrum_master_id_box', models.CharField(max_length=100, verbose_name='ID скрам-мастера в коробке')),
            ],
            options={
                'verbose_name': 'Скрам',
                'verbose_name_plural': 'Скрамы',
                'ordering': ['-id'],
            },
        ),
    ]
