# Generated by Django 4.1.7 on 2023-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0002_scrums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id_cloud', models.CharField(max_length=20, verbose_name='ID Бэклога облака')),
                ('backlog_id_box', models.CharField(max_length=20, verbose_name='ID Бэклога коробки')),
                ('scrum_cloud_id', models.CharField(max_length=20, verbose_name='ID скрама в облаке')),
                ('scrum_box_id', models.CharField(max_length=20, verbose_name='ID скрама в коробке')),
            ],
            options={
                'verbose_name': 'Бэклог',
                'verbose_name_plural': 'Бэклоги',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BitrixUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_cloud', models.CharField(max_length=20, verbose_name='ID юзера облака')),
                ('user_id_box', models.CharField(max_length=20, verbose_name='ID юзера коробки')),
                ('email', models.CharField(max_length=100, verbose_name='EMAIL')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Юзер битрикса',
                'verbose_name_plural': 'Юзеры битрикса',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_id_cloud', models.CharField(max_length=20, verbose_name='ID спринта в облаке')),
                ('sprint_id_box', models.CharField(max_length=20, verbose_name='ID спринта в коробке')),
                ('scrum_cloud_id', models.CharField(max_length=20, verbose_name='ID скрама в облаке')),
                ('scrum_box_id', models.CharField(max_length=20, verbose_name='ID скрама в коробке')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='scrums',
            name='scrum_box_id',
            field=models.CharField(max_length=20, verbose_name='ID скрама в коробке'),
        ),
        migrations.AlterField(
            model_name='scrums',
            name='scrum_cloud_id',
            field=models.CharField(max_length=20, verbose_name='ID скрама в облаке'),
        ),
    ]
