# Generated by Django 4.1.7 on 2023-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0003_backlog_bitrixusers_sprint_alter_scrums_scrum_box_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='sprint_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название спринта'),
        ),
    ]
