# Generated by Django 4.1.7 on 2023-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0004_sprint_sprint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_id_cloud', models.CharField(max_length=20, verbose_name='ID эпика в облаке')),
                ('epic_id_box', models.CharField(max_length=20, verbose_name='ID эпика в коробке')),
                ('scrum_cloud_id', models.CharField(max_length=20, verbose_name='ID скрама в облаке')),
                ('scrum_box_id', models.CharField(max_length=20, verbose_name='ID скрама в коробке')),
                ('epic_name', models.CharField(max_length=200, verbose_name='Название эпика')),
            ],
            options={
                'verbose_name': 'Эпик',
                'verbose_name_plural': 'Эпики',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScrumTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id_cloud', models.CharField(max_length=20, verbose_name='ID задачи в облаке')),
                ('task_id_box', models.CharField(max_length=20, verbose_name='ID задачи в коробке')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
    ]
