# Generated by Django 4.1.7 on 2023-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0005_epic_scrumtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id_cloud', models.CharField(max_length=20, verbose_name='ID коммента в облаке')),
                ('comment_id_box', models.CharField(max_length=20, verbose_name='ID коммента в коробке')),
                ('author_id_cloud', models.CharField(max_length=20, verbose_name='ID автора в облаке')),
                ('author_id_box', models.CharField(max_length=20, verbose_name='ID автора в коробке')),
                ('author_mail_cloud', models.CharField(max_length=100, verbose_name='EMAIL автора')),
            ],
            options={
                'verbose_name': 'Комментарий задачи',
                'verbose_name_plural': 'Комментарии задач',
                'ordering': ['-id'],
            },
        ),
    ]
