# Generated by Django 4.1.7 on 2023-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0006_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='epic',
            name='epic_files',
            field=models.CharField(blank=True, max_length=350, verbose_name='Файлы в эпике'),
        ),
        migrations.AddField(
            model_name='scrumtask',
            name='stage_id_box',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID стадии задачи в коробке'),
        ),
        migrations.AddField(
            model_name='scrumtask',
            name='stage_id_cloud',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID стадии задачи в облаке'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='files_in_comments',
            field=models.CharField(blank=True, max_length=350, verbose_name='Файлы в комментарие'),
        ),
    ]
