# Generated by Django 4.1.7 on 2023-03-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0008_alter_kanban_options_kanban_sprint_id_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='author_mail_cloud',
            new_name='author_mail',
        ),
    ]
