# Generated by Django 4.1.7 on 2023-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0009_rename_author_mail_cloud_taskcomment_author_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrums',
            name='scrum_master_id_box',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID скрам-мастера в коробке'),
        ),
        migrations.AlterField(
            model_name='scrums',
            name='scrum_master_id_cloud',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID скрам-мастера в облаке'),
        ),
    ]
