# Generated by Django 4.1.7 on 2023-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0010_alter_scrums_scrum_master_id_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='backlog_id_box',
            field=models.CharField(max_length=20, null=True, verbose_name='ID Бэклога коробки'),
        ),
    ]
