# Generated by Django 4.1.7 on 2023-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0011_alter_backlog_backlog_id_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='epic_files',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Файлы в эпике'),
        ),
    ]
