# Generated by Django 4.1.7 on 2023-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0012_alter_epic_epic_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumtask',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во комментов'),
        ),
        migrations.AddField(
            model_name='scrumtask',
            name='scrum_box_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID скрама в коробке'),
        ),
        migrations.AddField(
            model_name='scrumtask',
            name='scrum_cloud_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID скрама в облаке'),
        ),
    ]
