# Generated by Django 4.1.7 on 2023-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0013_scrumtask_comments_count_scrumtask_scrum_box_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='files_in_comments',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Файлы в комментарие'),
        ),
    ]
