# Generated by Django 4.1.7 on 2023-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0017_alter_kanbanstages_stages_id_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrums',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
