# Generated by Django 4.1.7 on 2023-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_transfer', '0018_scrums_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumtask',
            name='comments_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Кол-во комментов'),
        ),
    ]
